### ISSUE TITLE
Once a spam adress is blacklisted under banned sender does it automatically block also its sender ip????

### ISSUE THREAD

**Issue by topstarnetwork** [baruwaproject/baruwa#75]
Once a spam adress is blacklisted under banned sender does it automatically block also its sender ip????

Or I have to look for its ip from logs and add it also under banned sender list?

**Comment by fluxlabs** [comment]
Only blocks address.

--
Jeremy McSpadden | Flux Labs
Local - 850-250-5590x501<tel:850-250-5590;501> | Mobile - 850-890-2543<tel:850-890-2543>
Fax - 850-254-2955<tel:850-254-2955> | Toll Free - 877-699-FLUX<tel:877-699-FLUX>
Web - http://www.fluxlabs.net<http://www.fluxlabs.net/>


On Jun 10, 2015, at 2:51 PM, Heather Raffaella Riverso <notifications@github.com<mailto:notifications@github.com>> wrote:


Once a spam adress is blacklisted under banned sender does it automatically block also its sender ip????

Or I have to look for its ip from logs and add it also under banned sender list?

-

**Comment by topstarnetwork** [comment]
Thanks.
Do all banned adresses listed under a domain name get blocked full baruwa server wide or do I have to add those blacklist on each baruwa user domains if I want them banned server wide?

**Comment by fluxlabs** [comment]
Depends on how you add them.

If you add the from domain - yahoo.com<http://yahoo.com>
And to domain - yourdom.com<http://yourdom.com>

Then anyone sending form yahoo.com<http://yahoo.com> to yourdom.com<http://yourdom.com> will be blocked.

If you add from domain - yahoo.com<http://yahoo.com>
And to domain - blank

Then anyone sending from yahoo.com<http://yahoo.com> server wide will be blocked.

Or you could do - user@yahoo.com<mailto:user@yahoo.com> to user@yourdom.com<mailto:user@yourdom.com>


--
Jeremy McSpadden | Flux Labs
Local - 850-250-5590x501<tel:850-250-5590;501> | Mobile - 850-890-2543<tel:850-890-2543>
Fax - 850-254-2955<tel:850-254-2955> | Toll Free - 877-699-FLUX<tel:877-699-FLUX>
Web - http://www.fluxlabs.net<http://www.fluxlabs.net/>


On Jun 10, 2015, at 3:00 PM, Heather Raffaella Riverso <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks.
Do all banned adresses listed under a domain name get blocked full baruwa server wide or do I have to add those blacklist on each baruwa user domains if I want them banned server wide?

-

**Comment by topstarnetwork** [comment]
This screenshot show all blacklist banned domains http://awesomescreenshot.com/0d54z1yg44
I blocked for heather@trans-world.org

But wat I want to do is block them for all bruwa users not only for heather@trans-world.org

For exemple I want to block all spam adress for all baruwa users like for exemple

trans-world.org
host-space.org
luf-finder.com

etc...................


I want that all users who ahve a account on baruwa my spam list is aslo blocked for all those users so is it possible to do that from my own baruwa heather@trans-world.org account or do I have start adding banned adresses from baruwa admin panel and not baruwa user panel instead?????


How can I block spam banned adresses baruwa server wide for all present and future users account?

**Comment by fluxlabs** [comment]
Correct. An admin account will over ride all users add. Login as admin and set your global bans.

--
Jeremy McSpadden | Flux Labs
Local - 850-250-5590x501<tel:850-250-5590;501> | Mobile - 850-890-2543<tel:850-890-2543>
Fax - 850-254-2955<tel:850-254-2955> | Toll Free - 877-699-FLUX<tel:877-699-FLUX>
Web - http://www.fluxlabs.net<http://www.fluxlabs.net/>


On Jun 10, 2015, at 3:43 PM, Heather Raffaella Riverso <notifications@github.com<mailto:notifications@github.com>> wrote:


This screenshot show all blacklist banned domains http://awesomescreenshot.com/0d54z1yg44
I blocked for heather@trans-world.org<mailto:heather@trans-world.org>

But wat I want to do is block them for all bruwa users not only for heather@trans-world.org<mailto:heather@trans-world.org>

For exemple I want to block all spam adress for all baruwa users like for exemple

trans-world.org<http://trans-world.org>
host-space.org<http://host-space.org>
luf-finder.com<http://luf-finder.com>

etc...................

I want that all users who ahve a account on baruwa my spam list is aslo blocked for all those users so is it possible to do that from my own baruwa heather@trans-world.org<mailto:heather@trans-world.org> account or do I have start adding banned adresses from baruwa admin panel and not baruwa user panel instead?????

How can I block spam banned adresses baruwa server wide for all present and future users account?

-

**Comment by topstarnetwork** [comment]
so what I added on heather@trans-world.org won't block those spams server wide then?

**Comment by fluxlabs** [comment]
Not unless that user is an admin. And if you specified it for just an email.

--
Jeremy McSpadden | Flux Labs
Local - 850-250-5590x501<tel:850-250-5590;501> | Mobile - 850-890-2543<tel:850-890-2543>
Fax - 850-254-2955<tel:850-254-2955> | Toll Free - 877-699-FLUX<tel:877-699-FLUX>
Web - http://www.fluxlabs.net<http://www.fluxlabs.net/>


On Jun 10, 2015, at 4:05 PM, Heather Raffaella Riverso <notifications@github.com<mailto:notifications@github.com>> wrote:


so what I added on heather@trans-world.org<mailto:heather@trans-world.org> won't block those spams server wide then?

-

**Comment by topstarnetwork** [comment]
One more question baruwa doc says that baruwa is developped on django framework but when I check its files there no django at all,
can you tell me wich python framework baruwa is developped with?

**Comment by topstarnetwork** [comment]
can you tell me wich python framework baruwa is developped with?
