### ISSUE TITLE
Baruwa login not working

### ISSUE THREAD

**Issue by moshaiky** [baruwaproject/baruwa#79]
Im getting below error after login to baruwa interface.

Starting subprocess with file monitor
Starting server in PID 1777.
serving on 0.0.0.0:5000 view at http://127.0.0.1:5000

Error - <class 'sqlalchemy.exc.OperationalError'>: (OperationalError) FATAL:  password authentication failed for user "baruwa"
FATAL:  password authentication failed for user "baruwa"
 None None
URL: http://198.255.106.100:5000/login?__logins=0&came_from=/
File '/home/baruwa/px/local/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
  app_iter = self.application(environ, sr_checker)
File '/home/baruwa/px/local/lib/python2.7/site-packages/repoze/who/middleware.py', line 69 in __call__
  auth_ids = self.authenticate(environ, classification, ids)
File '/home/baruwa/px/local/lib/python2.7/site-packages/baruwa/lib/auth/middleware.py', line 178 in authenticate
  userid = plugin.authenticate(environ, identity)
File '/home/baruwa/px/local/lib/python2.7/site-packages/repoze/who/plugins/sa.py', line 166 in authenticate
  user = self.get_user(identity['login'])
File '/home/baruwa/px/local/lib/python2.7/site-packages/repoze/who/plugins/sa.py', line 64 in get_user
  return query.one()
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2184 in one
  ret = list(self)
File '/home/baruwa/px/local/lib/python2.7/site-packages/baruwa/lib/caching_query.py', line 77 in __iter__
  return Query.__iter__(self)
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2227 in __iter__
  return self._execute_and_instances(context)
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2240 in _execute_and_instances
  close_with_result=True)
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2231 in _connection_from_session
  **kw)
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py', line 784 in connection
  close_with_result=close_with_result)
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py', line 788 in _connection_for_bind
  return self.transaction._connection_for_bind(engine)
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py', line 313 in _connection_for_bind
  conn = bind.contextual_connect()
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 2489 in contextual_connect
  self.pool.connect(),
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/pool.py', line 236 in connect
  return _ConnectionFairy(self).checkout()
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/pool.py', line 401 in __init__
  rec = self._connection_record = pool._do_get()
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/pool.py', line 822 in _do_get
  return self._create_connection()
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/pool.py', line 189 in _create_connection
  return _ConnectionRecord(self)
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/pool.py', line 282 in __init__
  self.connection = self.__connect()
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/pool.py', line 344 in __connect
  connection = self.__pool._creator()
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py', line 80 in connect
  return dialect.connect(*cargs, **cparams)
File '/home/baruwa/px/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py', line 281 in connect
  return self.dbapi.connect(*cargs, **cparams)
File '/home/baruwa/px/local/lib/python2.7/site-packages/psycopg2/__init__.py', line 164 in connect
  conn = _connect(dsn, connection_factory=connection_factory, async=async)
File '/home/baruwa/px/local/lib/python2.7/site-packages/eventlet/support/psycopg2_patcher.py', line 46 in eventlet_wait_callback
  state = conn.poll()
OperationalError: (OperationalError) FATAL:  password authentication failed for user "baruwa"
FATAL:  password authentication failed for user "baruwa"
 None None

CGI Variables
-------------
  CONTENT_TYPE: 'application/x-www-form-urlencoded'
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate'
  HTTP_ACCEPT_LANGUAGE: 'en-US,en;q=0.8'
  HTTP_CACHE_CONTROL: 'max-age=0'
  HTTP_CONNECTION: 'keep-alive'
  HTTP_COOKIE: 'baruwa=d1e11c890267551a2ddaa5d98fb40be908ff97ad3fc82c207e16431e8a6b6a314d461be6'
  HTTP_HOST: '198.255.106.100:5000'
  HTTP_ORIGIN: 'http://198.255.106.100:5000'
  HTTP_REFERER: 'http://198.255.106.100:5000/accounts/login?came_from=http%3A%2F%2F198.255.106.100%3A5000%2F'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36'
  PATH_INFO: '/login'
  QUERY_STRING: '__logins=0&came_from=/'
  REMOTE_ADDR: '182.48.233.10'
  REQUEST_METHOD: 'POST'
  SERVER_NAME: '0.0.0.0'
  SERVER_PORT: '5000'
  SERVER_PROTOCOL: 'HTTP/1.1'

WSGI Variables
--------------
  application: <baruwa.lib.auth.middleware.BaruwaPAM object at 0x7fcf119ce910>
  paste.cookies: (<SimpleCookie: baruwa='d1e11c890267551a2ddaa5d98fb40be908ff97ad3fc82c207e16431e8a6b6a314d461be6'>, 'baruwa=d1e11c890267551a2ddaa5d98fb40be908ff97ad3fc82c207e16431e8a6b6a314d461be6')
  paste.httpserver.proxy.host: 'dummy'
  paste.httpserver.proxy.scheme: 'http'
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x7fcf05d6bb90>
  paste.parsed_dict_querystring: (MultiDict([('__logins', '0'), ('came_from', '/')]), '__logins=0&came_from=/')
  paste.parsed_querystring: ([('__logins', '0'), ('came_from', '/')], '__logins=0&came_from=/')
  paste.registry: <paste.registry.Registry object at 0x7fcf02abb150>
  paste.throw_errors: True
  repoze.who.application: <HTTPFound at 0x7fcf02ab72d0 302 Found>
  repoze.who.logger: <logging.Logger object at 0x7fcf05d5efd0>
  repoze.who.plugins: {'authorization_md': <repoze.what.middleware.AuthorizationMetadata object at 0x7fcf1418f910>, 'form': <FriendlyFormPlugin 140527135885072>, 'baruwa_pop3_auth': <baruwa.lib.auth.pop3auth.BaruwaPOPAuthPlugin object at 0x7fcf06051c90>, 'baruwa_smtp_auth': <baruwa.lib.auth.smtpauth.BaruwaSMTPAuthPlugin object at 0x7fcf06051a50>, 'baruwa_radius_auth': <baruwa.lib.auth.radiusauth.BaruwaRadiusAuthPlugin object at 0x7fcf05d96190>, 'sa_auth': <repoze.who.plugins.sa.SQLAlchemyAuthenticatorPlugin object at 0x7fcf06040dd0>, 'auth_tkt': <AuthTktCookiePlugin 140527132797648>, 'baruwa_imap_auth': <baruwa.lib.auth.imapauth.BaruwaIMAPAuthPlugin object at 0x7fcf05d98f10>, 'sa_md': <repoze.who.plugins.sa.SQLAlchemyUserMDPlugin object at 0x7fcf05d980d0>, 'baruwa_ldap_auth': <BaruwaLDAPAuthPlugin 140527135885520>}
  webob._body_file: (<_io.BufferedReader>, <socket._fileobject object at 0x7fcf02b19250 length=46>)
  webob._parsed_post_vars: (MultiDict([('login', u'baruwa'), ('password', '******'), ('lang', u'en')]), <_io.BufferedReader>)
  webob._parsed_query_vars: (GET([(u'__logins', u'0'), (u'came_from', u'/')]), '__logins=0&came_from=/')
  webob.is_body_readable: True
  webob.is_body_seekable: False
  wsgi process: 'Multithreaded'
------------------------------------------------------------

            <p>Additionally an error occurred while sending the &lt;weberror.reporter.EmailReporter object at 0x7fcf02a08d50&gt; report:

            <pre>Traceback (most recent call last):
  File "/home/baruwa/px/local/lib/python2.7/site-packages/weberror/errormiddleware.py", line 450, in send_report
    rep.report(exc_data)
  File "/home/baruwa/px/local/lib/python2.7/site-packages/weberror/reporter.py", line 54, in report
    self.to_addresses, msg.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 742, in sendmail
    raise SMTPRecipientsRefused(senderrs)
SMTPRecipientsRefused: {'baruwa@localhost': (504, '5.5.2 <baruwa@localhost>: Recipient address rejected: need fully-qualified address')}
</pre>
            </p>^C2016-11-06 20:38:22,862 INFO  [paste.httpserver.ThreadPool] [MainThread] Shutting down threadpool
Traceback (most recent call last):
  File "/home/baruwa/px/bin/paster", line 11, in <module>
    sys.exit(run())
  File "/home/baruwa/px/local/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/home/baruwa/px/local/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/home/baruwa/px/local/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/home/baruwa/px/local/lib/python2.7/site-packages/paste/script/serve.py", line 319, in command
    serve()
  File "/home/baruwa/px/local/lib/python2.7/site-packages/paste/script/serve.py", line 303, in serve
    server(app)
  File "/home/baruwa/px/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 189, in server_wrapper
    **context.local_conf)
  File "/home/baruwa/px/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/home/baruwa/px/local/lib/python2.7/site-packages/paste/httpserver.py", line 1361, in server_runner

**Comment by akissa** [comment]
The community edition is EOL and EOS - http://marc.info/?l=baruwa&m=146243390106536&w=2
